CREATE SCHEMA IF NOT EXISTS PRACTICA DEFAULT CHARACTER SET latin1 ;
USE PRACTICA;

CREATE TABLE PRACTICA.em_empleados
  (
   ID_EMPLEADO 				INT(7) PRIMARY KEY NOT NULL,	
   TX_NIF 					VARCHAR(9) unique,									
   TX_NOMBRE 				VARCHAR(30) NOT NULL,			
   TX_APELLIDO1 			VARCHAR(40) NOT NULL,			
   TX_APELLIDO2 			VARCHAR(40) NOT NULL,			
   F_NACIMIENTO				DATE  NOT NULL,								
   N_TELEFONO1 				VARCHAR(12) NOT NULL unique,						
   N_TELEFONO2 				VARCHAR(12) NOT NULL,						
   TX_EMAIL 				VARCHAR(40) NOT NULL unique,						
   F_ALTA 					DATE  NOT NULL,		
   F_BAJA					DATE,
   CX_EDOCIVIL 				CHAR(1) NOT NULL,							
   B_FORMACIONU 			CHAR(1) NOT NULL	                      
);

CREATE TABLE PRACTICA.pr_proyectos
(  
   ID_PROYECTO 				INT(5) PRIMARY KEY NOT NULL,
   TX_DESCRIPCION 			VARCHAR(125) NOT NULL,
   F_INICIO 				DATE NOT NULL,
   F_FIN 					DATE,
   F_BAJA					DATE,
   TX_LUGAR 				VARCHAR(30),
   TX_OBSERVACIONES 		VARCHAR(300)
);

CREATE TABLE PRACTICA.pr_empleados_proyecto
(
   ID_PROYECTO 				INT(5) NOT NULL,
   ID_EMPLEADO 				INT(7) NOT NULL,
   F_ALTA					DATE,
   CONSTRAINT PK_PR_EMPLEADOS_PROYECTO PRIMARY KEY (ID_PROYECTO, ID_EMPLEADO)
);



ALTER TABLE PRACTICA.em_empleados
MODIFY ID_EMPLEADO INT AUTO_INCREMENT;

ALTER TABLE PRACTICA.pr_proyectos
MODIFY ID_PROYECTO INT AUTO_INCREMENT;

ALTER TABLE PRACTICA.pr_proyectos
ADD COLUMN IMAGEN_URL VARCHAR(255);

ALTER TABLE PRACTICA.pr_empleados_proyecto ADD CONSTRAINT FK_PR_EMPLEADOS_PROYECTO_EM_EMPLEADOS_01 FOREIGN KEY (ID_EMPLEADO) REFERENCES PRACTICA.EM_EMPLEADOS (ID_EMPLEADO);
ALTER TABLE PRACTICA.pr_empleados_proyecto ADD CONSTRAINT FK_PR_EMPLEADOS_PROYECTO_PR_PROYECTOS_02 FOREIGN KEY (ID_PROYECTO) REFERENCES PRACTICA.PR_PROYECTOS (ID_PROYECTO);

select * from PRACTICA.em_empleados ;
delete from PRACTICA.em_empleados where 1=1;
